import { LandParcel, Alert, NDVIDataPoint } from '@/types';

export const mockParcels: LandParcel[] = [
  {
    id: '1',
    name: 'Ferma Bărăgan - Grâu',
    coordinates: [
      [44.65, 26.85],
      [44.65, 26.95],
      [44.55, 26.95],
      [44.55, 26.85],
    ],
    ndviIndex: 0.85,
    status: 'healthy',
    area: 120.5,
  },
  {
    id: '2',
    name: 'Câmpia Dunării - Porumb',
    coordinates: [
      [44.45, 26.65],
      [44.45, 26.80],
      [44.35, 26.80],
      [44.35, 26.65],
    ],
    ndviIndex: 0.32,
    status: 'fire',
    area: 85.2,
    damageEstimate: 145000,
  },
  {
    id: '3',
    name: 'Zona Brăila - Floarea Soarelui',
    coordinates: [
      [45.30, 27.90],
      [45.30, 28.05],
      [45.20, 28.05],
      [45.20, 27.90],
    ],
    ndviIndex: 0.45,
    status: 'flood',
    area: 95.7,
    damageEstimate: 98000,
  },
  {
    id: '4',
    name: 'Podișul Transilvaniei - Cartof',
    coordinates: [
      [46.55, 23.55],
      [46.55, 23.70],
      [46.45, 23.70],
      [46.45, 23.55],
    ],
    ndviIndex: 0.78,
    status: 'healthy',
    area: 65.3,
  },
  {
    id: '5',
    name: 'Banatul - Vie',
    coordinates: [
      [45.75, 21.20],
      [45.75, 21.35],
      [45.65, 21.35],
      [45.65, 21.20],
    ],
    ndviIndex: 0.72,
    status: 'healthy',
    area: 42.8,
  },
];

export const mockAlerts: Alert[] = [
  {
    id: '1',
    type: 'fire',
    message: 'Incendiu detectat în Sectorul 4 - Parcela Sud',
    timestamp: new Date('2025-12-06T14:30:00'),
    sector: 'Sector 4, București',
    severity: 'high',
  },
  {
    id: '2',
    type: 'flood',
    message: 'Risc de inundație în Sectorul 2 - Nivel apă crescut',
    timestamp: new Date('2025-12-06T12:15:00'),
    sector: 'Sector 2, București',
    severity: 'medium',
  },
  {
    id: '3',
    type: 'warning',
    message: 'Alertă meteo: Temperaturi ridicate în Craiova',
    timestamp: new Date('2025-12-06T08:00:00'),
    sector: 'Craiova',
    severity: 'low',
  },
  {
    id: '4',
    type: 'fire',
    message: 'Focar de incendiu identificat în zona Câmpia Dunării',
    timestamp: new Date('2025-12-05T18:45:00'),
    sector: 'Câmpia Dunării',
    severity: 'high',
  },
  {
    id: '5',
    type: 'fire',
    message: 'Risc crescut de incendiu - vegetație uscată',
    timestamp: new Date('2025-12-05T10:20:00'),
    sector: 'Sector 3, București',
    severity: 'medium',
  },
  {
    id: '6',
    type: 'flood',
    message: 'Alertă inundație - râu depășit cota de atenție',
    timestamp: new Date('2025-12-05T16:00:00'),
    sector: 'Sector 5, București',
    severity: 'high',
  },
  {
    id: '7',
    type: 'flood',
    message: 'Precipitații abundente - risc de inundații locale',
    timestamp: new Date('2025-12-04T22:30:00'),
    sector: 'Sector 1, București',
    severity: 'medium',
  },
  {
    id: '8',
    type: 'warning',
    message: 'Scădere NDVI detectată - posibilă degradare vegetație',
    timestamp: new Date('2025-12-06T09:00:00'),
    sector: 'Sector 6, București',
    severity: 'medium',
  },
  {
    id: '9',
    type: 'warning',
    message: 'Anomalie vegetație identificată - verificare recomandată',
    timestamp: new Date('2025-12-05T14:15:00'),
    sector: 'Sector 2, București',
    severity: 'low',
  },
  {
    id: '10',
    type: 'warning',
    message: 'Stres hidric detectat în culturile de grâu',
    timestamp: new Date('2025-12-04T11:45:00'),
    sector: 'Cluj',
    severity: 'high',
  },
  {
    id: '11',
    type: 'warning',
    message: 'Vânt puternic prognozat pentru următoarele 24h',
    timestamp: new Date('2025-12-06T17:00:00'),
    sector: 'Timișoara',
    severity: 'medium',
  },
  {
    id: '12',
    type: 'warning',
    message: 'Avertizare grindină - verifică acoperirea culturilor',
    timestamp: new Date('2025-12-05T20:00:00'),
    sector: 'Iași',
    severity: 'high',
  },
  {
    id: '13',
    type: 'fire',
    message: 'Vegetație uscată în flăcări - intervenție pompieri',
    timestamp: new Date('2025-12-06T15:20:00'),
    sector: 'Brașov',
    severity: 'high',
  },
  {
    id: '14',
    type: 'flood',
    message: 'Inundații costiere - risc ridicat',
    timestamp: new Date('2025-12-06T11:10:00'),
    sector: 'Constanța',
    severity: 'medium',
  },
  {
    id: '15',
    type: 'ndvi',
    message: 'Scădere drastică NDVI - posibilă infecție dăunători',
    timestamp: new Date('2025-12-05T09:30:00'),
    sector: 'Suceava',
    severity: 'high',
  },
  {
    id: '16',
    type: 'warning',
    message: 'Cod galben de vânt puternic',
    timestamp: new Date('2025-12-06T13:45:00'),
    sector: 'Tulcea',
    severity: 'medium',
  },
  {
    id: '17',
    type: 'fire',
    message: 'Incendiu pădure - zona montană',
    timestamp: new Date('2025-12-04T16:20:00'),
    sector: 'Baia Mare',
    severity: 'high',
  },
  {
    id: '18',
    type: 'flood',
    message: 'Debite crescute pe râul Olt',
    timestamp: new Date('2025-12-05T21:00:00'),
    sector: 'Râmnicu Vâlcea',
    severity: 'medium',
  },
  {
    id: '19',
    type: 'ndvi',
    message: 'Monitorizare satelitară - stare optimă',
    timestamp: new Date('2025-12-06T10:00:00'),
    sector: 'Oradea',
    severity: 'low',
  },
  {
    id: '20',
    type: 'warning',
    message: 'Temperaturi scăzute - risc de îngheț târziu',
    timestamp: new Date('2025-12-06T06:30:00'),
    sector: 'Miercurea Ciuc',
    severity: 'high',
  },
  {
    id: '21',
    type: 'fire',
    message: 'Arderea miriștilor necontrolată',
    timestamp: new Date('2025-12-05T14:40:00'),
    sector: 'Alexandria',
    severity: 'medium',
  },
  {
    id: '22',
    type: 'flood',
    message: 'Creștere nivel Dunăre',
    timestamp: new Date('2025-12-06T18:15:00'),
    sector: 'Galați',
    severity: 'high',
  },
  {
    id: '23',
    type: 'ndvi',
    message: 'Deficit de umiditate în sol',
    timestamp: new Date('2025-12-05T12:00:00'),
    sector: 'Botoșani',
    severity: 'medium',
  },
  {
    id: '24',
    type: 'warning',
    message: 'Ceață densă - vizibilitate redusă',
    timestamp: new Date('2025-12-06T07:15:00'),
    sector: 'Sibiu',
    severity: 'low',
  },
  {
    id: '25',
    type: 'fire',
    message: 'Incendiu de vegetație în Delta Dunării',
    timestamp: new Date('2025-12-05T17:30:00'),
    sector: 'Delta Dunării',
    severity: 'high',
  },
];

export const mockNDVIData: NDVIDataPoint[] = [
  { date: 'Ian', value: 0.45 },
  { date: 'Feb', value: 0.48 },
  { date: 'Mar', value: 0.62 },
  { date: 'Apr', value: 0.78 },
  { date: 'Mai', value: 0.85 },
  { date: 'Iun', value: 0.82 },
  { date: 'Iul', value: 0.75 },
  { date: 'Aug', value: 0.68 },
  { date: 'Sep', value: 0.72 },
  { date: 'Oct', value: 0.65 },
  { date: 'Nov', value: 0.52 },
  { date: 'Dec', value: 0.48 },
];

export const suggestedPrompts = [
  'Analizează dimensiunea cicatricei de ardere',
  'Generează raport pentru asigurător',
  'Compară cu anul trecut',
  'Care este starea vegetației?',
];
